// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AreaControl.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

GPB_ENUM_FWD_DECLARE(Result);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - AreaControlRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface AreaControlRoot : GPBRootObject
@end

#pragma mark - AreaControlAuthorizationRequest

typedef GPB_ENUM(AreaControlAuthorizationRequest_FieldNumber) {
  AreaControlAuthorizationRequest_FieldNumber_UserId = 1,
  AreaControlAuthorizationRequest_FieldNumber_Tobe = 2,
};

/**
 * 主播 场控 申请
 **/
@interface AreaControlAuthorizationRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

/** to be or no to be. only the room owner can set tobe=false, */
@property(nonatomic, readwrite) BOOL tobe;

@end

#pragma mark - AreaControlAuthorizationResponse

typedef GPB_ENUM(AreaControlAuthorizationResponse_FieldNumber) {
  AreaControlAuthorizationResponse_FieldNumber_Result = 1,
};

/**
 * 返回
 **/
@interface AreaControlAuthorizationResponse : GPBMessage

@property(nonatomic, readwrite) enum Result result;

@end

/**
 * Fetches the raw value of a @c AreaControlAuthorizationResponse's @c result property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t AreaControlAuthorizationResponse_Result_RawValue(AreaControlAuthorizationResponse *message);
/**
 * Sets the raw value of an @c AreaControlAuthorizationResponse's @c result property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetAreaControlAuthorizationResponse_Result_RawValue(AreaControlAuthorizationResponse *message, int32_t value);

#pragma mark - AreaControlAuthorizationPush

typedef GPB_ENUM(AreaControlAuthorizationPush_FieldNumber) {
  AreaControlAuthorizationPush_FieldNumber_Uid = 1,
  AreaControlAuthorizationPush_FieldNumber_RoomId = 2,
  AreaControlAuthorizationPush_FieldNumber_FromId = 3,
  AreaControlAuthorizationPush_FieldNumber_Tobe = 4,
};

/**
 * 给提升着发送消息
 **/
@interface AreaControlAuthorizationPush : GPBMessage

/** you */
@property(nonatomic, readwrite, copy, null_resettable) NSString *uid;

/** the room */
@property(nonatomic, readwrite, copy, null_resettable) NSString *roomId;

/** from who */
@property(nonatomic, readwrite, copy, null_resettable) NSString *fromId;

@property(nonatomic, readwrite) BOOL tobe;

@end

#pragma mark - AreaControlBannedRequest

typedef GPB_ENUM(AreaControlBannedRequest_FieldNumber) {
  AreaControlBannedRequest_FieldNumber_UserId = 1,
  AreaControlBannedRequest_FieldNumber_Tobe = 2,
};

/**
 * 主播 场控 禁言
 **/
@interface AreaControlBannedRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

@property(nonatomic, readwrite) BOOL tobe;

@end

#pragma mark - AreaControlBannedResponse

typedef GPB_ENUM(AreaControlBannedResponse_FieldNumber) {
  AreaControlBannedResponse_FieldNumber_Result = 1,
};

/**
 * 返回
 **/
@interface AreaControlBannedResponse : GPBMessage

@property(nonatomic, readwrite) enum Result result;

@end

/**
 * Fetches the raw value of a @c AreaControlBannedResponse's @c result property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t AreaControlBannedResponse_Result_RawValue(AreaControlBannedResponse *message);
/**
 * Sets the raw value of an @c AreaControlBannedResponse's @c result property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetAreaControlBannedResponse_Result_RawValue(AreaControlBannedResponse *message, int32_t value);

#pragma mark - AreaControlBannedPush

typedef GPB_ENUM(AreaControlBannedPush_FieldNumber) {
  AreaControlBannedPush_FieldNumber_Uid = 1,
  AreaControlBannedPush_FieldNumber_RoomId = 2,
  AreaControlBannedPush_FieldNumber_FromId = 3,
  AreaControlBannedPush_FieldNumber_Tobe = 4,
};

/**
 * 给被禁言者发送消息
 **/
@interface AreaControlBannedPush : GPBMessage

/** you */
@property(nonatomic, readwrite, copy, null_resettable) NSString *uid;

/** the room */
@property(nonatomic, readwrite, copy, null_resettable) NSString *roomId;

/** from who */
@property(nonatomic, readwrite, copy, null_resettable) NSString *fromId;

@property(nonatomic, readwrite) BOOL tobe;

@end

#pragma mark - AreaControlKickOutRequest

typedef GPB_ENUM(AreaControlKickOutRequest_FieldNumber) {
  AreaControlKickOutRequest_FieldNumber_UserId = 1,
  AreaControlKickOutRequest_FieldNumber_Tobe = 2,
};

/**
 * 主播 场控 踢出房间
 **/
@interface AreaControlKickOutRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

@property(nonatomic, readwrite) BOOL tobe;

@end

#pragma mark - AreaControlKickOutResponse

typedef GPB_ENUM(AreaControlKickOutResponse_FieldNumber) {
  AreaControlKickOutResponse_FieldNumber_Result = 1,
};

/**
 * 返回
 **/
@interface AreaControlKickOutResponse : GPBMessage

@property(nonatomic, readwrite) enum Result result;

@end

/**
 * Fetches the raw value of a @c AreaControlKickOutResponse's @c result property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t AreaControlKickOutResponse_Result_RawValue(AreaControlKickOutResponse *message);
/**
 * Sets the raw value of an @c AreaControlKickOutResponse's @c result property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetAreaControlKickOutResponse_Result_RawValue(AreaControlKickOutResponse *message, int32_t value);

#pragma mark - AreaControlKickOutPush

typedef GPB_ENUM(AreaControlKickOutPush_FieldNumber) {
  AreaControlKickOutPush_FieldNumber_Uid = 1,
  AreaControlKickOutPush_FieldNumber_RoomId = 2,
  AreaControlKickOutPush_FieldNumber_FromId = 3,
  AreaControlKickOutPush_FieldNumber_Tobe = 4,
};

/**
 * 给被踢出房间者发送消息
 **/
@interface AreaControlKickOutPush : GPBMessage

/** you */
@property(nonatomic, readwrite, copy, null_resettable) NSString *uid;

/** the room */
@property(nonatomic, readwrite, copy, null_resettable) NSString *roomId;

/** from who */
@property(nonatomic, readwrite, copy, null_resettable) NSString *fromId;

@property(nonatomic, readwrite) BOOL tobe;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
