// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ExchangeKey.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

GPB_ENUM_FWD_DECLARE(Result);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - ExchangeKeyRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface ExchangeKeyRoot : GPBRootObject
@end

#pragma mark - ExchangeKeyRequest

typedef GPB_ENUM(ExchangeKeyRequest_FieldNumber) {
  ExchangeKeyRequest_FieldNumber_AesKey = 1,
};

/**
 * 请求
 **/
@interface ExchangeKeyRequest : GPBMessage

/** 需要加密 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *aesKey;

@end

#pragma mark - ExchangeKeyResponse

typedef GPB_ENUM(ExchangeKeyResponse_FieldNumber) {
  ExchangeKeyResponse_FieldNumber_Result = 1,
  ExchangeKeyResponse_FieldNumber_Message = 2,
};

/**
 * 响应
 **/
@interface ExchangeKeyResponse : GPBMessage

@property(nonatomic, readwrite) enum Result result;

@property(nonatomic, readwrite, copy, null_resettable) NSString *message;

@end

/**
 * Fetches the raw value of a @c ExchangeKeyResponse's @c result property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t ExchangeKeyResponse_Result_RawValue(ExchangeKeyResponse *message);
/**
 * Sets the raw value of an @c ExchangeKeyResponse's @c result property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetExchangeKeyResponse_Result_RawValue(ExchangeKeyResponse *message, int32_t value);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
