// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Gifts.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class GetGrabRedPackagesResultResponse_GrabRedPackagesResult;
@class Gift;
GPB_ENUM_FWD_DECLARE(Result);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum Gift_GiftType

/** 礼物类型 */
typedef GPB_ENUM(Gift_GiftType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  Gift_GiftType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 普通礼物 */
  Gift_GiftType_GiftTypeNormal = 0,

  /** 红包礼物 */
  Gift_GiftType_GiftTypeRedPackets = 1,
};

GPBEnumDescriptor *Gift_GiftType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL Gift_GiftType_IsValidValue(int32_t value);

#pragma mark - GiftsRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface GiftsRoot : GPBRootObject
@end

#pragma mark - Gift

typedef GPB_ENUM(Gift_FieldNumber) {
  Gift_FieldNumber_Type = 1,
  Gift_FieldNumber_Uuid = 2,
  Gift_FieldNumber_Order = 3,
  Gift_FieldNumber_Name = 4,
  Gift_FieldNumber_GoldCoins = 5,
  Gift_FieldNumber_AllowContinue = 6,
  Gift_FieldNumber_Hidden = 7,
  Gift_FieldNumber_Icon = 8,
  Gift_FieldNumber_Animation = 9,
};

/**
 * 礼物
 **/
@interface Gift : GPBMessage

/** 礼物类型 */
@property(nonatomic, readwrite) Gift_GiftType type;

/** 礼物UUID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *uuid;

/** 编号 */
@property(nonatomic, readwrite) int32_t order;

/** 礼物名字 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** 金币数 */
@property(nonatomic, readwrite) int64_t goldCoins;

/** 是否允许连发 */
@property(nonatomic, readwrite) BOOL allowContinue;

@property(nonatomic, readwrite) BOOL hidden;

@property(nonatomic, readwrite, copy, null_resettable) NSString *icon;

@property(nonatomic, readwrite) int32_t animation;

@end

/**
 * Fetches the raw value of a @c Gift's @c type property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t Gift_Type_RawValue(Gift *message);
/**
 * Sets the raw value of an @c Gift's @c type property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetGift_Type_RawValue(Gift *message, int32_t value);

#pragma mark - GetGiftListRequest

typedef GPB_ENUM(GetGiftListRequest_FieldNumber) {
  GetGiftListRequest_FieldNumber_UserId = 1,
};

/**
 * 获取礼物列表请求
 **/
@interface GetGiftListRequest : GPBMessage

/** 用户id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

@end

#pragma mark - GetGiftListResponse

typedef GPB_ENUM(GetGiftListResponse_FieldNumber) {
  GetGiftListResponse_FieldNumber_Result = 1,
  GetGiftListResponse_FieldNumber_Message = 2,
  GetGiftListResponse_FieldNumber_GiftArray = 3,
};

/**
 * 获取礼物列表响应
 **/
@interface GetGiftListResponse : GPBMessage

@property(nonatomic, readwrite) enum Result result;

@property(nonatomic, readwrite, copy, null_resettable) NSString *message;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Gift*> *giftArray;
/** The number of items in @c giftArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger giftArray_Count;

@end

/**
 * Fetches the raw value of a @c GetGiftListResponse's @c result property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t GetGiftListResponse_Result_RawValue(GetGiftListResponse *message);
/**
 * Sets the raw value of an @c GetGiftListResponse's @c result property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetGetGiftListResponse_Result_RawValue(GetGiftListResponse *message, int32_t value);

#pragma mark - SendGiftRequest

typedef GPB_ENUM(SendGiftRequest_FieldNumber) {
  SendGiftRequest_FieldNumber_Gift = 1,
  SendGiftRequest_FieldNumber_AllowMaxUser = 2,
  SendGiftRequest_FieldNumber_NeedAck = 3,
  SendGiftRequest_FieldNumber_Count = 4,
};

/**
 * 发送礼物请求
 **/
@interface SendGiftRequest : GPBMessage

/** 礼物 */
@property(nonatomic, readwrite, strong, null_resettable) Gift *gift;
/** Test to see if @c gift has been set. */
@property(nonatomic, readwrite) BOOL hasGift;

/** 允许多少人抢 */
@property(nonatomic, readwrite) int32_t allowMaxUser;

/** 需要确认 */
@property(nonatomic, readwrite) BOOL needAck;

/** 礼物数量 */
@property(nonatomic, readwrite) int32_t count;

@end

#pragma mark - SendGiftResponse

typedef GPB_ENUM(SendGiftResponse_FieldNumber) {
  SendGiftResponse_FieldNumber_Result = 1,
  SendGiftResponse_FieldNumber_Message = 2,
};

/**
 * 发送礼物响应
 **/
@interface SendGiftResponse : GPBMessage

@property(nonatomic, readwrite) enum Result result;

@property(nonatomic, readwrite, copy, null_resettable) NSString *message;

@end

/**
 * Fetches the raw value of a @c SendGiftResponse's @c result property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t SendGiftResponse_Result_RawValue(SendGiftResponse *message);
/**
 * Sets the raw value of an @c SendGiftResponse's @c result property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetSendGiftResponse_Result_RawValue(SendGiftResponse *message, int32_t value);

#pragma mark - GrabRedPackagesRequest

typedef GPB_ENUM(GrabRedPackagesRequest_FieldNumber) {
  GrabRedPackagesRequest_FieldNumber_GiftUuid = 1,
};

/**
 * 抢红包请求
 **/
@interface GrabRedPackagesRequest : GPBMessage

/** 红包UUID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *giftUuid;

@end

#pragma mark - GrabRedPackagesResponse

typedef GPB_ENUM(GrabRedPackagesResponse_FieldNumber) {
  GrabRedPackagesResponse_FieldNumber_Result = 1,
  GrabRedPackagesResponse_FieldNumber_Message = 2,
  GrabRedPackagesResponse_FieldNumber_GoldCoins = 3,
};

/**
 * 抢红包响应
 **/
@interface GrabRedPackagesResponse : GPBMessage

@property(nonatomic, readwrite) enum Result result;

@property(nonatomic, readwrite, copy, null_resettable) NSString *message;

/** 抢到的金币数 */
@property(nonatomic, readwrite) int64_t goldCoins;

@end

/**
 * Fetches the raw value of a @c GrabRedPackagesResponse's @c result property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t GrabRedPackagesResponse_Result_RawValue(GrabRedPackagesResponse *message);
/**
 * Sets the raw value of an @c GrabRedPackagesResponse's @c result property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetGrabRedPackagesResponse_Result_RawValue(GrabRedPackagesResponse *message, int32_t value);

#pragma mark - PushGift

typedef GPB_ENUM(PushGift_FieldNumber) {
  PushGift_FieldNumber_MessageId = 1,
  PushGift_FieldNumber_FromShowId = 2,
  PushGift_FieldNumber_FromUserId = 3,
  PushGift_FieldNumber_Level = 4,
  PushGift_FieldNumber_NickName = 5,
  PushGift_FieldNumber_Avatar = 6,
  PushGift_FieldNumber_NeedAck = 7,
  PushGift_FieldNumber_Gift = 8,
  PushGift_FieldNumber_Count = 9,
};

/**
 * 礼物推送通知
 **/
@interface PushGift : GPBMessage

/** 消息id */
@property(nonatomic, readwrite) int64_t messageId;

/** 展示id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *fromShowId;

/** 消息发送者 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *fromUserId;

/** 等级 */
@property(nonatomic, readwrite) int32_t level;

/** 昵称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *nickName;

/** 头像 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *avatar;

/** 需要确认 */
@property(nonatomic, readwrite) BOOL needAck;

/** 礼物 */
@property(nonatomic, readwrite, strong, null_resettable) Gift *gift;
/** Test to see if @c gift has been set. */
@property(nonatomic, readwrite) BOOL hasGift;

/** 礼物个数 */
@property(nonatomic, readwrite) int32_t count;

@end

#pragma mark - PushGiftAck

typedef GPB_ENUM(PushGiftAck_FieldNumber) {
  PushGiftAck_FieldNumber_FromUserId = 1,
  PushGiftAck_FieldNumber_MessageId = 2,
};

/**
 * 消息推送确认
 **/
@interface PushGiftAck : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *fromUserId;

@property(nonatomic, readwrite) int64_t messageId;

@end

#pragma mark - GetGrabRedPackagesResultRequest

typedef GPB_ENUM(GetGrabRedPackagesResultRequest_FieldNumber) {
  GetGrabRedPackagesResultRequest_FieldNumber_UserId = 1,
  GetGrabRedPackagesResultRequest_FieldNumber_GiftUuid = 2,
};

/**
 * 获取抢红包结果请求
 **/
@interface GetGrabRedPackagesResultRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

/** 红包UUID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *giftUuid;

@end

#pragma mark - GetGrabRedPackagesResultResponse

typedef GPB_ENUM(GetGrabRedPackagesResultResponse_FieldNumber) {
  GetGrabRedPackagesResultResponse_FieldNumber_Result = 1,
  GetGrabRedPackagesResultResponse_FieldNumber_FromUserId = 2,
  GetGrabRedPackagesResultResponse_FieldNumber_MessageId = 3,
  GetGrabRedPackagesResultResponse_FieldNumber_RedpacksArray = 4,
};

/**
 * 获取抢红包结果响应
 **/
@interface GetGrabRedPackagesResultResponse : GPBMessage

@property(nonatomic, readwrite) enum Result result;

@property(nonatomic, readwrite, copy, null_resettable) NSString *fromUserId;

@property(nonatomic, readwrite) int64_t messageId;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<GetGrabRedPackagesResultResponse_GrabRedPackagesResult*> *redpacksArray;
/** The number of items in @c redpacksArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger redpacksArray_Count;

@end

/**
 * Fetches the raw value of a @c GetGrabRedPackagesResultResponse's @c result property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t GetGrabRedPackagesResultResponse_Result_RawValue(GetGrabRedPackagesResultResponse *message);
/**
 * Sets the raw value of an @c GetGrabRedPackagesResultResponse's @c result property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetGetGrabRedPackagesResultResponse_Result_RawValue(GetGrabRedPackagesResultResponse *message, int32_t value);

#pragma mark - GetGrabRedPackagesResultResponse_GrabRedPackagesResult

typedef GPB_ENUM(GetGrabRedPackagesResultResponse_GrabRedPackagesResult_FieldNumber) {
  GetGrabRedPackagesResultResponse_GrabRedPackagesResult_FieldNumber_UserId = 1,
  GetGrabRedPackagesResultResponse_GrabRedPackagesResult_FieldNumber_NickName = 2,
  GetGrabRedPackagesResultResponse_GrabRedPackagesResult_FieldNumber_GoldCoins = 3,
  GetGrabRedPackagesResultResponse_GrabRedPackagesResult_FieldNumber_Avatar = 4,
};

@interface GetGrabRedPackagesResultResponse_GrabRedPackagesResult : GPBMessage

/** 用户id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

/** 用户昵称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *nickName;

/** 抢红包结果 */
@property(nonatomic, readwrite) int64_t goldCoins;

@property(nonatomic, readwrite, copy, null_resettable) NSString *avatar;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
