// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Handshake.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

GPB_ENUM_FWD_DECLARE(Result);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - HandshakeRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface HandshakeRoot : GPBRootObject
@end

#pragma mark - HandshakeRequest

typedef GPB_ENUM(HandshakeRequest_FieldNumber) {
  HandshakeRequest_FieldNumber_Channel = 1,
  HandshakeRequest_FieldNumber_UseRsa = 2,
  HandshakeRequest_FieldNumber_PublicKey = 3,
};

/**
 * 请求
 **/
@interface HandshakeRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *channel;

@property(nonatomic, readwrite) BOOL useRsa;

@property(nonatomic, readwrite, copy, null_resettable) NSString *publicKey;

@end

#pragma mark - HandshakeResponse

typedef GPB_ENUM(HandshakeResponse_FieldNumber) {
  HandshakeResponse_FieldNumber_Result = 1,
  HandshakeResponse_FieldNumber_Message = 2,
  HandshakeResponse_FieldNumber_PublicKey = 3,
};

/**
 * 响应
 **/
@interface HandshakeResponse : GPBMessage

@property(nonatomic, readwrite) enum Result result;

@property(nonatomic, readwrite, copy, null_resettable) NSString *message;

@property(nonatomic, readwrite, copy, null_resettable) NSString *publicKey;

@end

/**
 * Fetches the raw value of a @c HandshakeResponse's @c result property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t HandshakeResponse_Result_RawValue(HandshakeResponse *message);
/**
 * Sets the raw value of an @c HandshakeResponse's @c result property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetHandshakeResponse_Result_RawValue(HandshakeResponse *message, int32_t value);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
