// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Handshake.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "Handshake.pbobjc.h"
 #import "Response.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - HandshakeRoot

@implementation HandshakeRoot

// No extensions in the file and none of the imports (direct or indirect)
// defined extensions, so no need to generate +extensionRegistry.

@end

#pragma mark - HandshakeRoot_FileDescriptor

static GPBFileDescriptor *HandshakeRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"live"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - HandshakeRequest

@implementation HandshakeRequest

@dynamic channel;
@dynamic useRsa;
@dynamic publicKey;

typedef struct HandshakeRequest__storage_ {
  uint32_t _has_storage_[1];
  NSString *channel;
  NSString *publicKey;
} HandshakeRequest__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "channel",
        .dataTypeSpecific.className = NULL,
        .number = HandshakeRequest_FieldNumber_Channel,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(HandshakeRequest__storage_, channel),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "useRsa",
        .dataTypeSpecific.className = NULL,
        .number = HandshakeRequest_FieldNumber_UseRsa,
        .hasIndex = 1,
        .offset = 2,  // Stored in _has_storage_ to save space.
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeBool,
      },
      {
        .name = "publicKey",
        .dataTypeSpecific.className = NULL,
        .number = HandshakeRequest_FieldNumber_PublicKey,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(HandshakeRequest__storage_, publicKey),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[HandshakeRequest class]
                                     rootClass:[HandshakeRoot class]
                                          file:HandshakeRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(HandshakeRequest__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\002\002\004b\000\003\t\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - HandshakeResponse

@implementation HandshakeResponse

@dynamic result;
@dynamic message;
@dynamic publicKey;

typedef struct HandshakeResponse__storage_ {
  uint32_t _has_storage_[1];
  Result result;
  NSString *message;
  NSString *publicKey;
} HandshakeResponse__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "result",
        .dataTypeSpecific.enumDescFunc = Result_EnumDescriptor,
        .number = HandshakeResponse_FieldNumber_Result,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(HandshakeResponse__storage_, result),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldHasEnumDescriptor),
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "message",
        .dataTypeSpecific.className = NULL,
        .number = HandshakeResponse_FieldNumber_Message,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(HandshakeResponse__storage_, message),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "publicKey",
        .dataTypeSpecific.className = NULL,
        .number = HandshakeResponse_FieldNumber_PublicKey,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(HandshakeResponse__storage_, publicKey),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[HandshakeResponse class]
                                     rootClass:[HandshakeRoot class]
                                          file:HandshakeRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(HandshakeResponse__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\001\003\t\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t HandshakeResponse_Result_RawValue(HandshakeResponse *message) {
  GPBDescriptor *descriptor = [HandshakeResponse descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:HandshakeResponse_FieldNumber_Result];
  return GPBGetMessageInt32Field(message, field);
}

void SetHandshakeResponse_Result_RawValue(HandshakeResponse *message, int32_t value) {
  GPBDescriptor *descriptor = [HandshakeResponse descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:HandshakeResponse_FieldNumber_Result];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
