// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Heartbeat.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

GPB_ENUM_FWD_DECLARE(Result);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - HeartbeatRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface HeartbeatRoot : GPBRootObject
@end

#pragma mark - HeartbeatRequest

typedef GPB_ENUM(HeartbeatRequest_FieldNumber) {
  HeartbeatRequest_FieldNumber_Ping = 1,
};

/**
 * 请求
 **/
@interface HeartbeatRequest : GPBMessage

/** "ping"，需要填写字段，否则消息体为空 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ping;

@end

#pragma mark - HeartbeatResponse

typedef GPB_ENUM(HeartbeatResponse_FieldNumber) {
  HeartbeatResponse_FieldNumber_Result = 1,
  HeartbeatResponse_FieldNumber_Message = 2,
};

/**
 * 响应
 **/
@interface HeartbeatResponse : GPBMessage

@property(nonatomic, readwrite) enum Result result;

@property(nonatomic, readwrite, copy, null_resettable) NSString *message;

@end

/**
 * Fetches the raw value of a @c HeartbeatResponse's @c result property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t HeartbeatResponse_Result_RawValue(HeartbeatResponse *message);
/**
 * Sets the raw value of an @c HeartbeatResponse's @c result property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetHeartbeatResponse_Result_RawValue(HeartbeatResponse *message, int32_t value);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
