// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Response.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "Response.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - ResponseRoot

@implementation ResponseRoot

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - Enum Result

GPBEnumDescriptor *Result_EnumDescriptor(void) {
  static GPBEnumDescriptor *descriptor = NULL;
  if (!descriptor) {
    static const char *valueNames =
        "Succeeded\000InternalServerError\000UnknownErr"
        "or\000InvalidUserInfo\000InvalidUserIdOrPasswo"
        "rd\000InsufficientBalance\000UserExistsError\000U"
        "serNotExistsError\000InvalidParameters\000Room"
        "NotExistsError\000UserNotInTheRoomError\000IsS"
        "ignedInToday\000UnknownTaskUuid\000UserNotLogg"
        "ed\000";
    static const int32_t values[] = {
        Result_Succeeded,
        Result_InternalServerError,
        Result_UnknownError,
        Result_InvalidUserInfo,
        Result_InvalidUserIdOrPassword,
        Result_InsufficientBalance,
        Result_UserExistsError,
        Result_UserNotExistsError,
        Result_InvalidParameters,
        Result_RoomNotExistsError,
        Result_UserNotInTheRoomError,
        Result_IsSignedInToday,
        Result_UnknownTaskUuid,
        Result_UserNotLogged,
    };
    static const char *extraTextFormatInfo = "\016\000\t\000\001\023\000\002\014\000\003\017\000\004\027\000\005\023\000\006\017\000\007\022\000\010\021\000\t\022\000\n\025\000\013\017\000\014\014c\000\r\r\000";
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(Result)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:Result_IsValidValue
                              extraTextFormatInfo:extraTextFormatInfo];
    if (!OSAtomicCompareAndSwapPtrBarrier(nil, worker, (void * volatile *)&descriptor)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL Result_IsValidValue(int32_t value__) {
  switch (value__) {
    case Result_Succeeded:
    case Result_InternalServerError:
    case Result_UnknownError:
    case Result_InvalidUserInfo:
    case Result_InvalidUserIdOrPassword:
    case Result_InsufficientBalance:
    case Result_UserExistsError:
    case Result_UserNotExistsError:
    case Result_InvalidParameters:
    case Result_RoomNotExistsError:
    case Result_UserNotInTheRoomError:
    case Result_IsSignedInToday:
    case Result_UnknownTaskUuid:
    case Result_UserNotLogged:
      return YES;
    default:
      return NO;
  }
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
