// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LiveUsers.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

GPB_ENUM_FWD_DECLARE(LiveResult);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum LiveUsersLoginRequest_Type

/** 类型 */
typedef GPB_ENUM(LiveUsersLoginRequest_Type) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  LiveUsersLoginRequest_Type_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 推流 */
  LiveUsersLoginRequest_Type_Pusher = 0,

  /** 拉流 */
  LiveUsersLoginRequest_Type_Puller = 1,
};

GPBEnumDescriptor *LiveUsersLoginRequest_Type_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL LiveUsersLoginRequest_Type_IsValidValue(int32_t value);

#pragma mark - Enum LiveUsersLoginResponse_Result

typedef GPB_ENUM(LiveUsersLoginResponse_Result) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  LiveUsersLoginResponse_Result_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 未知错误 */
  LiveUsersLoginResponse_Result_UnknownError = 0,

  /** 成功 */
  LiveUsersLoginResponse_Result_Succeeded = 1,

  /** 参数错误 */
  LiveUsersLoginResponse_Result_InvalidParameter = 2,

  /** 用户未登录错误 */
  LiveUsersLoginResponse_Result_UserNotLogged = 3,

  /** 用户名或密码错误 */
  LiveUsersLoginResponse_Result_InvalidUserIdOrPassword = 4,

  /** 服务器内部出错 */
  LiveUsersLoginResponse_Result_InternalServerError = 5,
};

GPBEnumDescriptor *LiveUsersLoginResponse_Result_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL LiveUsersLoginResponse_Result_IsValidValue(int32_t value);

#pragma mark - LiveUsersRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface LiveUsersRoot : GPBRootObject
@end

#pragma mark - LiveUsersLoginRequest

typedef GPB_ENUM(LiveUsersLoginRequest_FieldNumber) {
  LiveUsersLoginRequest_FieldNumber_Type = 1,
  LiveUsersLoginRequest_FieldNumber_UserId = 2,
  LiveUsersLoginRequest_FieldNumber_Token = 3,
  LiveUsersLoginRequest_FieldNumber_RoomId = 4,
};

/**
 * 登录请求
 **/
@interface LiveUsersLoginRequest : GPBMessage

/**
 * 推流客户端需要填写用户id可以不用填写房间id
 * 拉流客户端需要填写用户id和房间id
 **/
@property(nonatomic, readwrite) LiveUsersLoginRequest_Type type;

/** 用户id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

/** 令牌 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *token;

/** 房间id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *roomId;

@end

/**
 * Fetches the raw value of a @c LiveUsersLoginRequest's @c type property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t LiveUsersLoginRequest_Type_RawValue(LiveUsersLoginRequest *message);
/**
 * Sets the raw value of an @c LiveUsersLoginRequest's @c type property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetLiveUsersLoginRequest_Type_RawValue(LiveUsersLoginRequest *message, int32_t value);

#pragma mark - LiveUsersLoginResponse

typedef GPB_ENUM(LiveUsersLoginResponse_FieldNumber) {
  LiveUsersLoginResponse_FieldNumber_Result = 1,
  LiveUsersLoginResponse_FieldNumber_Message = 2,
};

/**
 * 登录响应
 **/
@interface LiveUsersLoginResponse : GPBMessage

/** 登录结果 */
@property(nonatomic, readwrite) LiveUsersLoginResponse_Result result;

/** 结果描述 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *message;

@end

/**
 * Fetches the raw value of a @c LiveUsersLoginResponse's @c result property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t LiveUsersLoginResponse_Result_RawValue(LiveUsersLoginResponse *message);
/**
 * Sets the raw value of an @c LiveUsersLoginResponse's @c result property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetLiveUsersLoginResponse_Result_RawValue(LiveUsersLoginResponse *message, int32_t value);

#pragma mark - LiveUsersLogoutRequest

typedef GPB_ENUM(LiveUsersLogoutRequest_FieldNumber) {
  LiveUsersLogoutRequest_FieldNumber_UserId = 1,
};

/**
 * 登出请求
 **/
@interface LiveUsersLogoutRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

@end

#pragma mark - LiveUsersLogoutResponse

typedef GPB_ENUM(LiveUsersLogoutResponse_FieldNumber) {
  LiveUsersLogoutResponse_FieldNumber_Result = 1,
  LiveUsersLogoutResponse_FieldNumber_Message = 2,
};

/**
 * 登出响应
 **/
@interface LiveUsersLogoutResponse : GPBMessage

@property(nonatomic, readwrite) enum LiveResult result;

@property(nonatomic, readwrite, copy, null_resettable) NSString *message;

@end

/**
 * Fetches the raw value of a @c LiveUsersLogoutResponse's @c result property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t LiveUsersLogoutResponse_Result_RawValue(LiveUsersLogoutResponse *message);
/**
 * Sets the raw value of an @c LiveUsersLogoutResponse's @c result property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetLiveUsersLogoutResponse_Result_RawValue(LiveUsersLogoutResponse *message, int32_t value);

#pragma mark - LiveUsersOtherLoginRequest

typedef GPB_ENUM(LiveUsersOtherLoginRequest_FieldNumber) {
  LiveUsersOtherLoginRequest_FieldNumber_Address = 1,
};

/**
 * 异地登录请求
 **/
@interface LiveUsersOtherLoginRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *address;

@end

#pragma mark - LiveUsersOtherLoginResponse

typedef GPB_ENUM(LiveUsersOtherLoginResponse_FieldNumber) {
  LiveUsersOtherLoginResponse_FieldNumber_Result = 1,
  LiveUsersOtherLoginResponse_FieldNumber_Message = 2,
};

/**
 * 异地登录响应
 **/
@interface LiveUsersOtherLoginResponse : GPBMessage

@property(nonatomic, readwrite) enum LiveResult result;

@property(nonatomic, readwrite, copy, null_resettable) NSString *message;

@end

/**
 * Fetches the raw value of a @c LiveUsersOtherLoginResponse's @c result property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t LiveUsersOtherLoginResponse_Result_RawValue(LiveUsersOtherLoginResponse *message);
/**
 * Sets the raw value of an @c LiveUsersOtherLoginResponse's @c result property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetLiveUsersOtherLoginResponse_Result_RawValue(LiveUsersOtherLoginResponse *message, int32_t value);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
